- hosts: "*"
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Set Timezone for servers
      shell: timedatectl set-timezone Europe/Dublin
    
    - name: Add zsh support
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: True